#! /bin/bash

DOCKER_NAME="opinionanalyzer"
CONTAINER_NAME=$USER"-opinionanalyzer"
SRC="OpinionAnalyzer" # folder to propulse in docker container
DOCKER_USER_ID=$(id -u) # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=$(id -g)
CONTAINER_PORT=8001 # used in launch_container file
INNER_PORT=8001 